<TelaInicial>:
    orientation: 'vertical'
    spacing: 0

    Cabecalho:

    # Área Central
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 20

        # 1. Espaçador superior maior (empurra o Label para perto do centro)
        Widget:
            size_hint_y: 1.2

        # 2. O Label (fica um pouco acima do meio)
        Label:
            text: "Bem-vindo \nao \nPainel de Controle"
            font_size: '36sp'
            halign: 'center'
            valign: 'middle'
            bold: True
            color: 0.9, 0.9, 0.9, 1
            size_hint_y: None
            height: self.texture_size[1]
            text_size: self.width, None
            pos_hint: {'center_x': 0.5}

        # 3. O Botão (fica exatamente no meio / abaixo do Label)
        BotaoPrincipal:
            text: "PROSSEGUIR"
            pos_hint: {'center_x': 0.5, 'center_y': 0.42}

            on_release: root.abrir_MenuPrincipal(self)

        # 4. Espaçador inferior (mantém o botão equilibrado)
        Widget:
            size_hint_y: 1

    Rodape: